FROM alpine:3.21

# Instalar herramientas necesarias
RUN apk add --no-cache curl jq netcat-openbsd bash

# Copiar script de login
COPY docker/scripts/acestream-init.sh /usr/local/bin/acestream-init.sh
RUN chmod +x /usr/local/bin/acestream-init.sh

CMD ["/usr/local/bin/acestream-init.sh"]