FROM nginx:alpine

# Instalar sed
RUN apk add --no-cache sed

# Eliminar configuración por defecto
RUN rm /etc/nginx/conf.d/default.conf

# Copiar configuración
COPY config/nginx.conf /etc/nginx/nginx.conf

# Copiar el script desde la carpeta scripts/
COPY scripts/replace.sh /replace.sh

# Dar permisos de ejecución al script
RUN chmod +x /replace.sh

EXPOSE 3000

# Usar el script como comando de inicio
CMD ["/replace.sh"]