FROM openresty/openresty:alpine

# Copiar configuración de Nginx
COPY nginx.conf /usr/local/openresty/nginx/conf/nginx.conf

# Exponer puerto 80
EXPOSE 80

# Iniciar OpenResty en modo foreground
CMD ["/usr/local/openresty/bin/openresty", "-g", "daemon off;"]