FROM jopsis/acestream:arm64-v3.2.14-update

# instalar curl y jq
RUN apk add --no-cache curl jq

# copiar entrypoint
COPY docker/entrypoint-acestream.sh /entrypoint-acestream.sh
RUN chmod +x /entrypoint-acestream.sh

ENTRYPOINT ["/entrypoint-acestream.sh"]
